### ISSUE TITLE
Add deployment info to  BRCA Exchange Readme.md

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#1]
_From @melissacline on February 18, 2016 21:2_

At https://github.com/BD2KGenomics/brca, update the section pertaining to restarting the GA4GH reference server as needed.

_Copied from original issue: BD2KGenomics/brca-pipeline#139_

**Comment by melissacline** [comment]
Clean up the deployment scripts to deploy both the beta and production sites respectively.  Check the code into the brca-exchange github repo, along with a script to copy the deployment scripts to the home directory.  Update Readme.md to indicate the deployment process.  Some of this might involve moving steps from the brca-website github repo.

**Comment by maryjgoldman** [comment]
In this case, I think I don't think I'm the best reviewer for this. Assigning to @acthp for review.
