### ISSUE TITLE
add genome assembly labeling in convert_tsv_to_vcf.py

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#10]
convert_tsv_to_vcf.py produces vcf files that  indicate GRCh37 in all cases.  It needs a parameter to indicate the actual genome assembly.

**Comment by melissacline** [comment]
Molly, you've fixed this, correct?  Is the change checked into github?

**Comment by MollyZhang** [comment]
Yes this is fixed and change is checked in
