### ISSUE TITLE
New text on Expert Reviewed Portal

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#100]
This is the BRCA Exchange Clinical Space and contains all variants in the database but only displays expert-reviewed variant classifications provided to date by the ENIGMA consortium. The expert interpretations will become more fully populated pending accumulation of additional evidence and additional review.

**Comment by melissacline** [comment]
@maryjgoldman  I've missed the background on this.  See https://github.com/BD2KGenomics/brca-exchange/issues/164.  Do you think #162 duplicates this?  It's not exactly the same wording, but seems to be getting at the same point.

**Comment by maryjgoldman** [comment]
Yes, this was from an old email chain. I think the best thing is to go with the new text, especially since it basically says the same thing. Closing ...
