### ISSUE TITLE
Finish email support for community pages

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#11]

**Comment by melissacline** [comment]
Under the community pages, there is (or should be?) code to recover lost passwords and to send email to new members.  This couldn't be configured fully until the DNS registry was transferred to UCSC.  At this time, the transfer is almost complete.  

Check with Brian Craft on the details for further registration.

**Comment by melissacline** [comment]
The DNS registry has been transferred to UCSC.   We have set up the email address brcaexchange@gmail.com.  What is the next step?

**Comment by strbean** [comment]
I think this is all ready, I just need the password to brcaexchange@gmail.com

**Comment by strbean** [comment]
Email working for password reset and new account verification. Will test further tomorrow. 

Live on beta server.

**Comment by maryjgoldman** [comment]
Is this done as part of the Tier 1 cleanup?

**Comment by strbean** [comment]
Yep

**Comment by maryjgoldman** [comment]
A bit hard to test all the functionality since the community space is sparse right now, but from what I can see, this is good
