### ISSUE TITLE
add webservices to 'more' menu

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#117]
We will have swagger docs soon (as in within 2 weeks), and we could pull of a section for the parts of the API used for the GA4GH BRCA portal. We will also have the sample iPython notebook. So I think that the link should point to a page that describes the REST portal, a pointer to the Swagger docs, a pointer to the iPython notebook.

The Swagger docs will be available once we merge the http annotations

I hope this helps,

-Kevin

> On Sep 21, 2016, at 4:07 PM, Benedict Paten benedict@soe.ucsc.edu wrote:
> 
> We would probably make a simple web page, like the help pages, that would contain instructions and info, linking to the appropriate URLs, ideally to swagger docs. Kevin?
> 
> On Wed, Sep 21, 2016 at 12:56 PM, Mary Goldman mary@soe.ucsc.edu wrote:
> 
> ```
> That sounds like a great idea! I'll make a ticket.
> 
> To be completely clear, what should the webservices link point to? The python notebook? An informational page about the endpoints?
> 
> Best,
> Mary
> 
> On Wed, Sep 21, 2016 at 11:44 AM, Benedict Paten <benedict@soe.ucsc.edu> wrote:
> 
>     Awesome. Mary, we need to add issues (if they don't already exist) to link from brca exchange.org to these services - as an advert. I'm thinking that webservices should be an option in the more tab.
> 
>     Benedict
>     (from phone, forgive extra typos)
> ```

**Comment by zfisch** [comment]
@maryjgoldman @melissacline 
Is this an existing page somewhere or a link to an external site? I see the link to "Webservices for API data access" in the versioning wireframes, but I'm not clear where this is supposed to go.

**Comment by maryjgoldman** [comment]
The static page will be added by @david4096. He's still generating it, AFAIK.

**Comment by david4096** [comment]
Hi you can see what I've done here. https://github.com/BD2KGenomics/brca-exchange/pull/145

There's a small blurb in the About This Site, a link that says "API" in the footer, and a link to some generated documentation.

**Comment by zfisch** [comment]
I'm afraid I'm still not clear where the link in the more menu is supposed to go. Is it supposed to point to the same place as the API link in the footer (about/api)?

**Comment by melissacline** [comment]
It makes sense to me that the link in the More menu would go to the same page as the API link in the footer.  @david4096 ?

**Comment by david4096** [comment]
Hey, I'm happy to readjust as you see fit! I did not make any additions to links in the header. The "about this site" does have a brief blurb to link to the API page, as well as the footer.
