### ISSUE TITLE
Update the loading script to not re-load a variant unless it has changed

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#129]

**Comment by zfisch** [comment]
We'll need to discuss this depending on how we relate variants to versions. Specifically, if we add a foreign key from variant to version table, we'll need to decide if we always insert new variants regardless of changes, or if we only insert new variants and then update the version_id on non-updated variants.

**Comment by melissacline** [comment]
@zfisch : does a blank field for the change type indicate no change?
