### ISSUE TITLE
In BRCA pseudonym generator, tack a “g” into all genomic coordinates.

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#140]

**Comment by zfisch** [comment]
@melissacline is this only necessary on the pyhgvs_Genomic_Coordinate_38 column or should it be on 36 and 37 as well?

**Comment by maryjgoldman** [comment]
I'm pretty sure it's for all: 38, 37 and 36

**Comment by melissacline** [comment]
Yes, it's for all: 38, 37 and 36.
