### ISSUE TITLE
Refine the Expert Reviewed / All Data portal toggle

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#16]

**Comment by melissacline** [comment]
From the 7/21 EGG call:
- in All Data mode, the blue box next to BRCA Exchange at the top of the screen reads "Research".  This should be "All Data"
- In All Data mode, the text in the cream box above the variant table begins "This is the BRCA Exchange Research Space".  Replace that with "This is all BRCA Exchange variant data".
- In All Data mode, replace the button label "Show Expert Reviewed Data" with "Show Expert Reviewed Data Only".
- In Expert Reviewed mode, at the bottom of the Variant Details page, the button "Research Information on this Variant" should read "Show All Data on this Variant".
- The button at the bottom of the Variant Details page in Expert Reviewed mode should read "Show Expert Reviewed Data on this Variant".
- The disclaimer screen contains the following text:
"You are leaving the BRCA Exchange Clinical Space and entering the Research Space. The BRCA Exchange Research Space contains a much larger set of variant data than the Clinical Space, and includes variants that have not yet been subject to expert review by the ENIGMA consortium. Pathogenicity assignments are from the original submitters.

Are you sure you want to leave the Clinical Space (Default View) and enter the Research Space?"
and should be replaced with this text:
"You are leaving the BRCA Exchange Expert Reviewed portal and entering the portal to view all variant data. This portal contains a much larger set of variant data than the Expert Reviewed portal, and includes variants that have not yet been subject to expert review by the ENIGMA consortium. Pathogenicity assignments are from the original submitters.

Are you sure you want to leave the Expert Reviewed portal to view all variant data?" 

- and clean up any other little inconsistencies you notice in the wording.  Check with Mary as needed.

**Comment by strbean** [comment]
Did we decide to have a blue label in the header in Expert Reviewed mode?

**Comment by melissacline** [comment]
That would make sense.  Let's try that...

**Comment by strbean** [comment]
Just about finished with this, but I found a pre-existing bug where toggling mode from the button at the bottom of the Variant Detail doesn't update the navbar (the blue tag remains the same). Working on that but it is tricky based on the architecture.
