### ISSUE TITLE
Change wording on front page

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#18]
Right now it reads:
"Just type in box above and use auto-complete to search for BRCA1 or BRCA2 variants. For more information about the BRCA1 and BRCA2 genes, genetic variation, and cancer, please click the About link at the top of the page."

We will need to change this due to our navigation changing. Also, this is an opportunity to make our 'search help' more professional and less jargony (remove 'auto-complete')

**Comment by melissacline** [comment]
This wording came from David Haussler.  I believe that we've moved far from the time when David suggested the wording, and don't need to adhere to this wording request exactly.

**Comment by maryjgoldman** [comment]
New wording per Zack:
"The BRCA Exchange advances our understanding of the genetic basis of breast cancer, ovarian cancer and other diseases by pooling data on BRCA1/2 genetic variants and corresponding clinical data from around the world. Search for BRCA1 or BRCA2 variants above. This website is supported by the BRCA Exchange of the Global Alliance for Genomics and Health."

**Comment by strbean** [comment]
This is up on beta now. Should it have some formatting? Bolding BRCA Exchange looks kinda nice xD

**Comment by melissacline** [comment]
I _like_ that idea!

**Comment by maryjgoldman** [comment]
Change to be: 'The BRCA Exchange aims to advance our understanding ...
