### ISSUE TITLE
Assess why a large number of LOVD variants were removed

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#185]

**Comment by melissacline** [comment]
Looking at NM_000059.3:c.6785T>C, a BRCA2 variant.
Sadly, it appears on the LOVD web site: http://databases.lovd.nl/shared/variants/0000030879.
It is present in the file BRCA2.txt
It appears in both removed.tsv and added.tsv.  In removed.tsv, its genomic HGVS string is chr13:g.32341140:T>C.  In added.tsv, its HGVS string is chr13:g.32341140:>C.  Note that this is actually a different variant, an insertion rather than a substitution.  It doesn't appear that these variants were merged (there's nothing in equivalent_variants.pkl).  
This change (from chr13:g.32341140:T>C to chr13:g.32341140:>C) appears to happen during variant-merging.py, looking at its output.
The change is happening because the REF column is empty for this variant in the input VCF.  That's looking at the VCF from Zack's tarball.  It looks like the REF column is empty for all variants in the VCF file.  @zfisch , can you verify this?
If so, the next question is _why_ the REF column is empty.  The other time I've seen this behavior turned out to be due to a bug in CrossMap, for which the workaround was installing a special version of CrossMap.

**Comment by melissacline** [comment]
Supporting this theory, it looks like all of the LOVD variants in built.tsv are listed as ins or dup according to the genomic HGVS strings.  This is definitely off.  Yay, closing in on the mystery!

**Comment by zfisch** [comment]
A quick note after reading "It doesn't appear that these variants were merged (there's nothing in equivalent_variants.pkl": not all merged variants are in equivalent_variants.pkl. There are other places where merges can take place, e.g. during the variant_standardize call.

**Comment by zfisch** [comment]
Sure enough, all refs are lost immediately following execution of crossmap. Furthermore, when trying to simply iterate through the records using `import vcf` and a for loop to print all the records, errors are encountered in every vcf file we have of LOVD.

**Comment by zfisch** [comment]
Found an error in CompileVCFFiles.py, lines 761 and 782. Should be lovdAnnotation, not exLOVDAnnotation. Rerunning data with fixes now to examine output. 

Code for reference: https://github.com/BD2KGenomics/brca-exchange/blob/master/pipeline/luigi/CompileVCFFiles.py#L761

**Comment by melissacline** [comment]
@zfisch Errors are encountered in every VCF file of LOVD?  Does that include the ones built prior to execution of CrossMap?  

It's good to hear that the lost refs look like the CrossMap problem again, not some completely different and unknown problem....  Does the newer version of CrossMap fix the problem?

**Comment by zfisch** [comment]
Yep.

I'm finding problems with lovd2vcf as well. specifically that the exLOVDAnnotation matches BRCA1.txt and BRCA2.txt for exLOVD exactly, while sharedLOVDAnnotation does not match either BRCA1.txt or BRCA2.txt for sharedLOVD (both are different).

**Comment by melissacline** [comment]
Wow!

What do you mean that sharedLOVDAnnoation doesn't match either BRCA txt?  In what way do they not match?

If necessary, we could use a Plan B of not updating any of the LOVD data for this cycle.  It's perhaps best to get the rest of the data out there, and then go back and fix up LOVD over the next month are so.

**Comment by zfisch** [comment]
The headers don't match between the sharedLOVDAnnotation and the extracted files directly from LOVD.

From sharedLOVDAnnotation:

dna_change
dna_change_genomic
rna_change
protein_change
haplotype
functionalanalysis_technique
functionalanalysis_result
exon
effect
published_as
db_id
vip
variant_remarks
reference
dbsnp_id
genetic_origin
segregation
frequency
re_site
methylation
owner

From BRCA1.txt:

effect
exon
dna_change
rna_change
protein_change
haplotype
functionalanalysis_technique
functionalanalysis_result
dna_change_genomic
published_as
iscn
db_id
variant_remarks
reference
dbsnp_id
germline_somatic_de_novo
segregation
frequency
re_site
vip
methylation
owner

From BRCA2.txt:

effect
exon
dna_change
rna_change
protein_change
haplotype
functionalanalysis_result
functionalanalysis_technique
dna_change_genomic
published_as
db_id
vip
variant_remarks
reference
dbsnp_id
genetic_origin
segregation
frequency
re_site
methylation
owner

**Comment by zfisch** [comment]
As an experiment, I made a new annotation that matches brca2.txt and ran only that data (instead of both brca1 and brca2) and I still lost refs after running CrossMap.py.

**Comment by melissacline** [comment]
What version of CrossMap is running?  The last we saw, CrossMap.py 0.2.3
was dropping the reference bases, but CrossMap.py  0.2.4 was working.  pip
install CrossMap still installs 0.2.3.  0.2.4 is available from
SourceForge.  It looks like 0.2.5 just came out, but I don't know anything
about it yet.

**Comment by zfisch** [comment]
Looks like I'm running 0.2.3. Our install instructions read " pip install CrossMap (8/25/16: install from" and that's it, but it is included in requirements.txt without a version specified as well. I'll try updating to 0.2.4 and see what happens.

**Comment by zfisch** [comment]
Sure enough, that brings out refs back! A couple questions -- shall we update the documentation to ensure 0.2.4 or should we try 0.2.5? Also, would you like me to resolve the sharedLOVDAnnotation issues by dynamically generating the headers based on the input files or should that be left alone for now?

**Comment by melissacline** [comment]
- Let's test out CrossMap version 0.2.5.  If it works, we can add a clause
to the pipeline requirements of CrossMap 0.2.4 or greater.
- I'm not so sure about the headers because I'm less clear on what's going
on.  What I see are different headers for BRCA1.txt, BRCA2.txt (known to be
bad) and sharedLOVDAnnotation.  I'm deducing from the message that
sharedLOVDAnnotation has the headers as downloaded, is that correct?

How about a hangout tomorrow morning?  I don't need to be anywhere until
10:30 AM Pacific time...

**Comment by zfisch** [comment]
Hey Melissa! Just saw this, I can hangout any time today/tonight. I'm currently experimenting with 0.2.5. Please send an invite through email to schedule a hangout whenever works for you. I'll see it through email much more quickly than here.
