### ISSUE TITLE
compile list of variant-merging changes that would effect original data output

### ISSUE THREAD

**Issue by zfisch** [BD2KGenomics/brca-exchange#190]

**Comment by zfisch** [comment]
@melissacline do you know what state the code was in when the beta release (the build that produced the old old data -- aggregated.tsv) took place? If there's a specific commit I can go back to, I can produce a diff and detail all of the changes that were made to produce the updated old data.

**Comment by melissacline** [comment]
@zfisch the code that corresponded to that change should be here (f95da9d37a4bd5a5d317ab7f5332cb34ac843c5a in the old brca-pipeline repo): https://github.com/BD2KGenomics/brca-pipeline/commit/f95da9d37a4bd5a5d317ab7f5332cb34ac843c5a#diff-35b24d0d3086a57fa075dcd98cae23e5

Remember how Brian merged the brca-exchange, brca-website and brca-pipeline repos in August?  This was before the merge.

**Comment by zfisch** [comment]
Perfect, thanks!

**Comment by zfisch** [comment]
I'm not sure how detailed to get with this, but a here's a high level overview of the major changes to the new pipeline that lead to different variant counts given the same data (i.e. total # of variants and which variants are merged):

1. We now adjust the position when refs are empty during variant equivalence testing (prevents off by one error).
2. We now throw out variants without a defined position by the time they enter equivalence testing.
3. We now remove variants where ref == alt.

There are many many other changes that affect the output, but they have a greater impact on the diff than merging and variant counts. Please let me know if they're of interest and how you would like them to be explained!
