### ISSUE TITLE
Update Gunnar's affiliation

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#197]
eventually, I’d like to have my affiliation updated on http://brcaexchange-dev.cloudapp.net:9001/about/thisSite
        and http://brcaexchange-dev.cloudapp.net:9001/about/history

**Comment by maryjgoldman** [comment]
Looks like this still has Gunnar's old affiliation on http://brcaexchange-dev.cloudapp.net/about/history.
