### ISSUE TITLE
Bring up two developer sandboxes

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#21]
@strbean , would you look into setting up two developer sandboxes, one for yourself and one for @zfisch ?  Feel free to use Brian for guidance, and if you find yourself stuck in need of some sort of resource, let me know and I'll look into getting you unstuck.  Thanks!

**Comment by strbean** [comment]
Brian is going to spin up a new VM for these today, and I'll talk with him about getting subdomains setup.
