### ISSUE TITLE
On the Release Notes page, order the previous data releases from most recent to least recent

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#231]

**Comment by maryjgoldman** [comment]
I am looking at this on dev and it doesn't appear to be in the correct order. Am I looking in the right place? @strbean

**Comment by strbean** [comment]
Hmmm, let me check. It might not be up on dev yet.

**Comment by zfisch** [comment]
i believe this was already resolved. probably just needs to be updated with latest on master.

**Comment by maryjgoldman** [comment]
This is not on dev. Moving back to ready for QA for now ...
