### ISSUE TITLE
False positive search results

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#236]
Reported by miguel de la hoya <mdhoya@hotmail.com>

I am a rather confused with the "search engine".

Just as an example, look to the attached screen capture.
If  I search for "c.5284T>G", I get as output c.5057T>A (instead of "no match").

I have been checking with other variants. If the variant is in BRCA exchange, the search engine finds it, but if the variant is not in BRCA exchange, you never get as an answer "no match", but one or sometimes several variants with no clear relationship with the search term. Also, sometimes, if the variant is in BRCA exchange you get as an answer the search term, but also other unrelated variants......I find this can be a bit confusing???????

**Comment by zfisch** [comment]
For clarification -- this has been identified as a potential pipeline issue where an incorrect synonym may be associated with a variant.

**Comment by zfisch** [comment]
My previous comment is partially incorrect. The problem occurs as a result of `term += ":*”` in the sanitise_term method of the search query (https://github.com/BD2KGenomics/brca-exchange/blob/master/website/django/data/views.py#L227). The intention of this line is to enable prefix search. We’re also using `.extra()` to run the modified query, which django advises against strongly in their documentation (https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.extra). Leaving as a note, continuing working toward a solution...

**Comment by zfisch** [comment]
The plot thickens... the `term += ":*”` (prefix enabler) does affect the flexibility of results from the search term, but removing it does not consistently address the issue.

E.G. with the prefix enabler in place, searching for `c.5284T>W` returns `c.5057T>A` (which it should not). if I replace the `W` with an `S` or `T`, I still get  `c.5057T>A` as a match. Searching `c.5284T>R`, however, returns no match. Capitalization of the last character also does not seem to affect the outcome.

 If I remove the prefix enabler,  `c.5284T>W`, `c.5284T>S`, `c.5284T>R` all return no match, but `c.5284T>T` still returns  `c.5057T>A`, which it shouldn't.

**Comment by melissacline** [comment]
Looking at built.tsv, here's what I can add.  c.5284T>W per se does not
appear in the variant set, while c.5057T>A does.  c.5057T>A has a synonym
of U43746.1:c.5284T>A.  U43746.1 is the transcript that many of the older
variants are annotated against, and particularly the BIC variants.  So now
I understand _why_ c.5284T>something is returning a hit
to c.5057T>something, although we probably don't want it to.  That needs
some rethinking.

Then there's the matter of whether or not those <somethings> are the same
nucleotide.  To muddy the water a bit, we have these wildcard characters (
http://www.bioinformatics.org/sms/iupac.html), by which W can represent
either A or T.  So then it makes sense that searching T>W would return T>A,
but it's odd that searching T>R does not...

This might be a good time to revisit the Mutalyzer API, and see what it
could do for us...

**Comment by zfisch** [comment]
Ok, this makes sense now. What's happening is the search is interpreting `c.5284T>W` as `"c.5284:*" AND "W:*"`, which returns `c.5057T>A` since it has both values in its index. notice you could also search `c.5284T>WWW` and it will still return `c.5057T>A` since www is a prefix of e.g. `www.ncbi.nlm.nih.gov`, but  `c.5284T>WWWW` will return no results.

**Comment by zfisch** [comment]
here are all the indexes for `c.5057T>A`:

'-08':19,45 '-09':18,44 '/clinvar/?term=scv000300821':79 '/wp-content/uploads/2016/06/enigma_rules_2015-03-26.pdf':27 '000050.2':69 '000059.3':63,65 '2':12 '2015':24 '2016':17,43 '612555':14 'a':33,67,76,89,93,96 'allele':29 'alleles':56 'based':48 'brca1/2':21 'brca2':61 'breast':6 'breast-ovarian':5 'brovca2':13 'c.5057t':66 'c.5284t':95 'cancer':8 'chr13':73,86,90 'classification':22 'clinvar':2,85 'concordant':80 'criteria':23 'curation':39,60 'disease':15 'encode':32 'enigma':1,20,57,83 'enigmaconsortium.org':26 'enigmaconsortium.org/wp-content/uploads/2016/06/enigma_rules_2015-03-26.pdf':25 'evidence':47 'evidence-based':46 'familial':9 'for':50 'functional':37 'g.31811549':91 'g.32339412':74 'g.32913549':87 'germline':40,54,59 'interpretation':52 'l1686':72 'leu1686ter':71 'lovd':3 'mutant':55 'network':49 'nm':62,64 'non':36 'non-functional':35 'np':68 'of':53 'omim':4 'ovarian':7 'p':70 'pathogenic':16,42,81,82,84 'predicted':30 'protein':38 'scv000300821':58 'scv000300821.2':41 'susceptibility':10 't':75,88,92 'the':51 'to':11,31 'truncated':34 'u43746.1':94 'variant':28 'www.ncbi.nlm.nih.gov':78 'www.ncbi.nlm.nih.gov/clinvar/?term=scv000300821':77 | '-08':19,45 '-09':18,44 '/clinvar/?term=scv000300821':79 '/wp-content/uploads/2016/06/enigma_rules_2015-03-26.pdf':27 '000050.2':69 '000059.3':63,65 '2':12 '2015':24 '2016':17,43 '612555':14 'a':33,67,76 'allele':29 'alleles':56 'based':48 'brca1/2':21 'brca2':61 'breast':6 'breast-ovarian':5 'brovca2':13 'c.5057t':66 'cancer':8 'chr13':73 'classification':22 'clinvar':2,85 'concordant':80 'criteria':23 'curation':39,60 'disease':15 'encode':32 'enigma':1,20,57,83 'enigmaconsortium.org':26 'enigmaconsortium.org/wp-content/uploads/2016/06/enigma_rules_2015-03-26.pdf':25 'evidence':47 'evidence-based':46 'familial':9 'for':50 'functional':37 'g.32339412':74 'germline':40,54,59 'interpretation':52 'l1686':72 'leu1686ter':71 'lovd':3 'mutant':55 'network':49 'nm':62,64 'non':36 'non-functional':35 'np':68 'of':53 'omim':4 'ovarian':7 'p':70 'pathogenic':16,42,81,82,84 'predicted':30 'protein':38 'scv000300821':58 'scv000300821.2':41 'susceptibility':10 't':75 'the':51 'to':11,31 'truncated':34 'variant':28 'www.ncbi.nlm.nih.gov':78 'www.ncbi.nlm.nih.gov/clinvar/?term=scv000300821':77
(2 rows)
