### ISSUE TITLE
Change the help pages to reflect feedback from Mandy Spurdle

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#256]

**Comment by maryjgoldman** [comment]
Do we have a description of what these changes were? I'm forgetting ....

**Comment by maryjgoldman** [comment]
Found it!

    in general genes BRCA1 and BRCA2 should be italicised (but proteins not)

I've got a github ticket for Joe to italicize the gene names in the Gene column.  I've italicized all the instances of BRCA1 and BRCA2 in the help text, about pages, etc., but have not italized BRCA.
 


    help pg. 
    not urgent but we need to update benign to match the terminology on the front pg....which is now listed as benign/little clinical significance

Done.  On this help page, how should I refer to Likely Benign variants?  There aren't any expert classifications as such, so it's not an urgent question... 
 
 

    more pg... 
    same...need to update benign on BRCA1/ BRCA2 and cancer pg. BRCA1/BRCA2 should be italicised when talking about the gene

This should be done now.
 

    could also be politicall correct to include more than just US pages. ask john burn he is filled with good ideas on this front. NICE?

Will do.
 


    history pg. 
    suggest following edit for accuracy (HVP and ENIGMA actually first proposed the meeting!)
    In collaboration with the Human Variome Project and ENIGMA representatives, on June 12-13, 2015, a meeting to further develop the vision for data sharing and expert BRCA variant classification took place at UNESCO headquarters in Paris, including representatives from many laboratories and organizations including Ambry Genetics, AstraZeneca, Annai Systems, ClinGen, ClinVar, Curoverse, DECIPHER, DNAnexus, [ENIGMA], Genetic Alliance, Genomics England, Illumina, Inserm, Invitae, LabCorp, LOVD, New England Journal of Medicine, Quest, SolveBio, World Health Organization and many others.

    At this meeting, the vision of a web portal to share ENIGMA expert-reviewed BRCA variant classifications was proposed.

I've made the text changes, but I'm not sure what you're indicating with the grey box [ENIGMA].  Are you suggesting some formatting changes?
