### ISSUE TITLE
follow up with david about ga4gh

### ISSUE THREAD

**Issue by zfisch** [BD2KGenomics/brca-exchange#269]

**Comment by david4096** [comment]
:) reporting 🔢 , just took a look at production and it seems like the changes haven't moved on from beta. Do you have an environment I can test against?

**Comment by zfisch** [comment]
hi david, right now your latest changes are in dev but not yet in beta. you can test against my dev machine at brcaexchange-dev.cloudapp.net:9002 for now, and I'll let you know when changes make it to beta.

in case it's helpful, the backend url is different on dev, beta, and prod. 

dev: 'http://brcaexchange-dev.cloudapp.net:9004'
beta: 'http://brcaexchange.cloudapp.net/backend'
prod: 'http://brcaexchange.org/backend'

**Comment by david4096** [comment]
Thanks @zfisch! Did you update the requirements for the dev instance? We got a new protobuf version and so I don't expect to see this error:

http://htmlpreview.github.io/?https://gist.githubusercontent.com/david4096/2621e4aee6831cccd99c10dffe3febb2/raw/83fcb6ad7c39466fbdb174a937b92782fc1da919/brca_exchange_ga4gh_dev_bug.html

**Comment by david4096** [comment]
Hey @zfisch just want to make sure you've got what you need from me for now. The problem was that the environment wasn't upgrading your packages. That could be fixed by recreating the environment with every install, or telling pip to `--upgrade`. I can get well formed responses from http://brcaexchange-dev.cloudapp.net:9004/data/ga4gh/v0.6.0a7 !

**Comment by zfisch** [comment]
Everything is good for now! We'll definitely want to retest when we go to beta, I'll give you a heads up.

To reiterate, we don't want to tell pip to upgrade because we want to maintain the existing versions of our dependencies for various reasons. If we wanted to upgrade, we wouldn't specify exact versions for dependencies in the requirements.txt file (rather minimum versions). It should be ok moving forward because the environments are better controlled in beta/prod, but I'll keep a close eye.
