### ISSUE TITLE
Missing "empty" designation on some change log items

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#289]
I'm seeing some things in the change log where something that is empty is going to something and there is only a "+" with the new thing, rather than the 'empty' logo (soon to be a new star!). Eg. Clinical Significance (ClinVar): +Likely benign http://brcaexchange-dev.cloudapp.net:9001/variant/23323

**Comment by strbean** [comment]
In that particular case, Clinical Significance (ClinVar) actually went from "Benign" to "Benign, Likely_benign".

The general case, however, wasn't handled. Fixed in PR.
