### ISSUE TITLE
Filter out changes to literature references when the first author is the same.

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#294]
See for example:  Literature Reference (exLOVD): Easton DF et al., Am J Hum Genet, 81: 873-883, 2007. Easton et al. 2007 
http://brcaexchange-dev.cloudapp.net:9001/variant/22376

**Comment by maryjgoldman** [comment]
This variant now looks much cleaner: http://brcaexchange-dev.cloudapp.net/variant/22376. However, I'm wondering why 'SCV Accession (ClinVar): -SCV000220269' got taken out of the change log. Was this a real change to begin with?

**Comment by maryjgoldman** [comment]
Never mind. The indexes on the variants are not the same btwn dev and production. Looking into this more
