### ISSUE TITLE
LOW PRIORITY: Need to make dates consistent everywhere they are displayed, including the change log. Always date month year (e.g. 2 Dec 2015)

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#298]

**Comment by zfisch** [comment]
Does this include overwriting the dates as they're seen in the `changes` column or only in the `date` column (see below? 

![date_inconsistencies](https://cloud.githubusercontent.com/assets/4503616/21370860/925bdf64-c6d3-11e6-806d-7bbef439e517.png)

**Comment by melissacline** [comment]
Good question!  @maryjgoldman , I think this issue was discussed when I was away.  I'm hoping you'll say that this applies only to dates that we generate (such as in the release date column), and not content that we import from the data sources.  Unifying imported content sounds like a hefty job...

**Comment by maryjgoldman** [comment]
I was thinking yes, but I realize that might not be possible.

**Comment by maryjgoldman** [comment]
@melissacline That's a really good point. I think we can push back on the Challenge folks with saying the content is from other data sources. As long as we have the dates we generate in the right format, I think that's the best we can do

**Comment by zfisch** [comment]
I could overwrite them in the ui without having to change the data itself, is this desirable?

**Comment by maryjgoldman** [comment]
How fragile would this be? Walk me through the logic the code would be following. Like 'if you see ##/##/## then translate it to day month year' ?

**Comment by zfisch** [comment]
lots of options depending -- we could use regex to identify dates (can catch an unlimited number of different formats but gets harder to write the more there are), i could try using the date library we already use (moment.js), or if it's as simple as only having dates in fields that have the word "date" in them it's even easier.

**Comment by strbean** [comment]
I believe all dates in the database are currently "MM/DD/YY" or "MM/DD/YYYY". If you tell moment.js that the format is "MM/DD/YYYY" it will gracefully handle dates in the format "MM/DD/YY" (which makes life way easier).

I feel like the biggest downside to this is making it harder to spot errors in the data down the road (if a date is in an unexpected format, for example), since we won't be seeing exactly what is in the DB anymore.

**Comment by maryjgoldman** [comment]
Zack and I discussed and decided to go ahead with using moment.js to reformat any field that has 'date' in the label. Won't work 100% of the time but seems fairly robust.

**Comment by zfisch** [comment]
yea -- I agree very much with joe. as long as people are ok with seeing an affected version of what's in the DB...

**Comment by maryjgoldman** [comment]
@strbean @zfisch True, though really we shouldn't be using the UI to spot pipeline issues. That should be happening before the data gets loaded up. So it's more about displaying the changes to the user

**Comment by zfisch** [comment]
k, ill make the change
