### ISSUE TITLE
Depending on engineering effort, we will either have text that is always there or conditional text to say if there are changes to the All Data portal that are not displayed on the Expert Reviewed page

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#299]

**Comment by zfisch** [comment]
If it's too tricky to apply the note conditionally, just add a note to all changelogs that says something like "there might be additional changes to this variant, click the all data link to see these changes".

**Comment by maryjgoldman** [comment]
How did we end up resolving this? I'm not seeing any text ...

**Comment by zfisch** [comment]
it's in code reviewing awaiting @strbean approval
