### ISSUE TITLE
When viewing the deleted variants, go directly to the variant table with deleted variants

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#307]
Currently, when you follow a Deleted Variants link from the Previous Data Releases page, you arrive at the Variants table with no variants shown, the message above the table saying "0 matching variants deleted in release X", and a message below the table saying "There are N deleted variants that matches your search. Click here to view these deleted variants.".  When you click on the link at "here", the variant table is shown with the deleted variants highlighted in light brown.  Instead of having this intermediate step with an empty table, go directly from the Previous Data Releases page to the view with the deleted variants highlighted in light brown.

The milestone for this issue is listed as Versioning 2.1.  But there are many issues to be addressed for Versioning 2.1, and if this issue can go in the next release if we start running out of time.

**Comment by maryjgoldman** [comment]
Yes, this is a known bug that @strbean brought to our attention when we first started the review period for Versioning 2.0. Not sure if Joe has made progress towards this or not.

**Comment by strbean** [comment]
This is fixed in master :)
