### ISSUE TITLE
Investigate why http://brcaexchange.org/variant/23323 has Date last updated (ClinVar) is 2015-12-01,2015-01-12

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#317]
Could be bc it was two variants in clinvar who got merged? Or a bug?

**Comment by zfisch** [comment]
No problem here, it's from a merge -- here are the two variants as extracted from ClinVar, one with date 1/12/15 and one with 12/1/15:

`NM_007294.3:c.548-80T>C	Evidence-based Network for the Interpretation of Germline Mutant Alleles (ENIGMA)	Benign	2015-01-12	SCV000244757	456252	germline	curation	chr17:43097369:A>G	BRCA1	None`

and 

`NM_007294.3:c.548-80T>C	University of Washington Department of Laboratory Medicine,University of Washington	Likely benign	2015-12-01	SCV000265011	496003	germline	clinical testing	chr17:43097369:A>G	BRCA1	None`
