### ISSUE TITLE
In the release notes, there are now two links to the Known Issues document

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#338]
See for example in http://brcaexchange-dev.cloudapp.net:9002/release/3:

Known issues: For the current list, see https://github.com/BD2KGenomics/brca-exchange/wiki/Known-Issues. 

To report new issues: please email brcaexchange@gmail.com.

Known issues with this release

**Comment by zfisch** [comment]
Ah yes, the version on dev is different than the version on beta. this issue has already been addressed.
