### ISSUE TITLE
Broken swagger document link

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#349]
In http://brcaexchange.org/about/api, this link 
(http://brcaexchange.org/backend/static/swagger/index.html) is linked to by:

The BRCA exchange exposes the interfaces necessary for accessing variant data, which are a subset of the interfaces the GA4GH defines. For a detailed description of the interface view the generated documentation.

**Comment by melissacline** [comment]
From Kevin: "Just to be clear, the fix that David has is to remove the link for now."

**Comment by zfisch** [comment]
@melissacline my understanding is that I should remove the link, is this correct?

**Comment by zfisch** [comment]
Looks like this link was removed by @david4096 on Nov 15th https://github.com/BD2KGenomics/brca-exchange/commit/a2cde704bd93caf5d7e52f0005cb6807266c2116 and has already been pushed to beta. I'm going to leave it as is for now.
