### ISSUE TITLE
add data use agreement under more menu to sandbox with video demo

### ISSUE THREAD

**Issue by zfisch** [BD2KGenomics/brca-exchange#370]
get data use agreement from melissa
add to more menu
include on dev sandbox with video demos

**Comment by melissacline** [comment]
Here is a Google doc with the text to go into the agreement: https://docs.google.com/document/d/1MRHxUCvPPiHIPedsCC1yX43mdn--IsXi294EK81HKxE/edit?usp=sharing

**Comment by zfisch** [comment]
This is now up at http://brcaexchange-dev.cloudapp.net:9002/about/dataUse.
