### ISSUE TITLE
Evaluate back end options for Community Pages signups

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#42]
From Mary:

Looks like there's quite a few options. Unsure which would be the best one. This is something that typically Brian C would look into as far as ease of implementation, features, etc.

Django email programs and templates (there are a ton): https://djangopackages.org/grids/g/email/. Maybe we can use one of these without mailchimp since several of them offer unsubscribe, etc. However, could not find email templates that were anything but text (ie. not professional looking). I searched for about 30 sec and then stopped so there could be things out there.

"Mandrill is a transactional email service offered by Mailchimp. There is an API client library for that too at https://pypi.python.org/pypi/mandrill/, "

Mandrill API: https://mandrillapp.com/api/docs/

Someone integrating django and mailchimp: http://qasimalbaqali.com/django-newsletter-app-with-mailchimp/

Note the djrill (django-mandrill interface) is no longer being maintained: https://djrill.readthedocs.io/en/v2.1/ and Mandrill is a paid service.

API for google contacts: https://developers.google.com/google-apps/contacts/v3/
You can add custom fields to google contacts: https://productforums.google.com/forum/?hl=en#!category-topic/gmail/contacts-and-sync/NaDweDetNGA

**Comment by strbean** [comment]
Sounds like we are going with MailChimp.

Two ways for MailChimp subscriptions to be done:
- A form hosted on brcaexchange
- A pop-out form from MailChimp

The latter is quicker. Is there a preference?

**Comment by maryjgoldman** [comment]
What does a pop-out from MailChimp look like? I've only seen it where the form is from MailChimp and embedded in the page. Like on xena.ucsc.edu. https://github.com/ucscXena/xena-ghost-template
