### ISSUE TITLE
Melissa and Molly to verify the data pipeline build instructions for Zack

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#43]
ClinVar is ready to go
Molly will take on 1000 Genomes next, and Melissa will take on ESP next.

**Comment by melissacline** [comment]
lovd is ready.  brca-pipeline/lovd/README.md contains verified instructions for building LOVD and exLOVD.  brca-pipeline/README.md contains a growing list of resources (prerequisites) for the build process.

**Comment by melissacline** [comment]
Question: The BIC download requires a userID and password.  If our github repo is public, how should we communicate these credentials to the pipeline?

**Comment by melissacline** [comment]
BIC is otherwise ready to go.

**Comment by melissacline** [comment]
ESP is ready.

**Comment by MollyZhang** [comment]
ENIGMA is ready

**Comment by zfisch** [comment]
Nice, just saw this ticket for the first time today. Thank you both for consistent updates. I just completed a monster luigi task for ESP, will need cleanup and installation adjustments later but just making it work first. It's accessible at https://github.com/BD2KGenomics/brca-exchange/blob/luigi/pipeline/luigi/CompileVCFFiles.py in case you're curious.

**Comment by melissacline** [comment]
ExAC is now ready.

**Comment by MollyZhang** [comment]
1000 genome is ready

**Comment by zfisch** [comment]
@MollyZhang could you clarify where to find the raw_files directory mentioned in the ENIGMA directory?

**Comment by MollyZhang** [comment]
@zfisch it's committed in the old brca-pipeline directory, 
Here:
https://github.com/BD2KGenomics/brca-pipeline/tree/master/enigma
