### ISSUE TITLE
Change fields required by role in Community Pages

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#48]
- Make Name and Role required
- Make email and password optional for patients

**Comment by maryjgoldman** [comment]
Right now displaying your email on the site is optional no matter what your role is. 

I think what this is mostly about is deciding how much we want to watch over patients shoulders to help them identify when they might be identifiable. Like, should we allow them to show their email? Should we allow them to give a city? A last name?

**Comment by maryjgoldman** [comment]
Also, can we make the 'Other' field required, if they pick 'Other'?
