### ISSUE TITLE
Add Data Provider category to the Community Pages

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#56]
Add a signup category for Data Providers to the Community Pages.  This category will represent organizations, not individuals.  For Data Providers, the First and Last names should be optional, as  Institution, Hospital or Company should be filled in instead.  I'm leaning towards _not_ requiring Institution, Hospital or Company, just to keep the code simple.

**Comment by maryjgoldman** [comment]
I also like not requiring the Institution too. This is a corner case and so not worth the code on our first round to do this.
