### ISSUE TITLE
Database:showVariant() should not modify its inputs

### ISSUE THREAD

**Issue by acthp** [BD2KGenomics/brca-exchange#62]
This is inappropriate for a 'show' method:

```javascript
row["Genomic_Coordinate_hg38"] = backend.trimSearchTerm(row["Genomic_Coordinate_hg38"]);
```

**Comment by melissacline** [comment]
Joe, would you look into this?  Is this doing some data cleaning that's inappropriate for a show method but is useful?  If so, let me know what the issue is with the data, so we can address it the next time the data is updated.

**Comment by strbean** [comment]
This is pretty odd, that trim function is intended for search queries! It limits the length to 200 characters. There aren't any variants nearly that long (longest one is 76 characters). I think it's safe to ditch that entirely.
