### ISSUE TITLE
Add command line arguments to CompileVcfFiles.py to specify data, resources and output paths

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#66]
It would be useful to have command line arguments to specify where to find the BRCA resources (e.g. hg38.fa.gz), the direcotry where the output VCF files are copied to, and a parent directory for each of the individual repo data directories (i.e ../brca/pipeline-data/data in the current script)

**Comment by zfisch** [comment]
Great idea, I'll start working these in today.

**Comment by zfisch** [comment]
@melissacline For clarification, is it safe to assume all BRCA resources will be in a single directory?

**Comment by zfisch** [comment]
Also, is it required that the files are copied to the output directory or is it ok to have them only created in the output directory? I.E in the current script, I only create the final vcf file in the output directory instead of creating it in the specific script file directory and then copy it to the output directory.

**Comment by melissacline** [comment]
@zfisch Yes, you can assume that all the BRCA resources will be in the same directory.  I'd like to keep the functionality that files are copied to the output directory, rather than having a single copy created in the output directory.  It can be useful to be able to refer back to the working directory for a repo, and see the output file along with the intermediate files.

**Comment by zfisch** [comment]
Ok, I'll need to add the copy functionality back into the script tomorrow. I did just push up a change to allow command line arguments for brca resources, a parent directory for individual data source files, and an output directory.
