### ISSUE TITLE
Crocodile Dundee doesn't appear on the map

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#70]
On http://brcaexchange-dev.cloudapp.net:9001/, I have signed up Crocodile Dundee under the email address mcline@ucsc.edu.  He doesn't appear on the map. I originally placed him in Alice Springs, Australia but moved him to Austin, Texas to see it that would help.  It didn't.  He also doesn't appear in the list of community members...

**Comment by strbean** [comment]
He needs to be approved through the admin interface! Which, from looking now, doesn't have the most functional interface (none of the CSS is loading).

**Comment by strbean** [comment]
I've approved your account and made it an admin, so if you visit http://brcaexchange-dev.cloudapp.net:9003/admin you can approve/edit/grant admin on other accounts. I'll do the same on the beta server.

**Comment by melissacline** [comment]
All good now.  Let's add a message to the screen to tell users who've just signed up that they'll be added to the list as soon as their entries are approved.  I'll create it as a separate issue.
