### ISSUE TITLE
Update the luigi pipeline with the updated BIC build instructions

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#72]
The README in brca-exchange/pipeline/bic contains some updated instructions.  It turns out that the old instructions involved doing the BIC mapping "the old way", which incurred loss of data.

**Comment by zfisch** [comment]
on it.

**Comment by zfisch** [comment]
I noticed that the new directions include downloading `bicAnnotation` from `cline@hgwdev.soe.ucsc.edu:public_html/BRCA/resources/bicAnnotation` into the BRCA_Resources directory. Is this the same bicAnnotation file that's already in the bic directory (I'm getting a refused connection btw)? If so, is there any reason to download it as part of this script or move it to BRCA_Resources?
