### ISSUE TITLE
Figure out why some community members appear in the listing but not on the map

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#77]
A couple users who appear in the Community Pages on http://brcaexchange-dev.cloudapp.net:9001/community?updateSuccess=true, but don't appear on the map, include Gunnar Ratsch (Zurich, Switzerland) and Nelson Mandela (Johannesburg, South Africa).  This might be a result of some limitations in the API, but we should understand for ourselves what those limitations are.

**Comment by strbean** [comment]
Looks like rate limiting from the Google geocoding api. Might need to cache
results server side.

**Comment by strbean** [comment]
Fix for this is mostly done, testing now.
