### ISSUE TITLE
scroll to error message if error in submitting a form

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#93]
This is for all pages. Right now it appears to users that hitting 'submit' doesn't do anything when in reality they forgot to fill out a field and we are giving them an error message. 

Scroll to the error message in this case

**Comment by strbean** [comment]
I think we want to add more detailed messages, such as specifying which required fields are missing below, right?

**Comment by maryjgoldman** [comment]
If it's cheap to do this, let's! Or highlight the missing fields? Whatever is easy to implement + helpful.
